# Generated by Django 4.1.5 on 2023-10-16 13:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('subtype', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('subcode', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('ipassword', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('category_year', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('id_country', models.UUIDField(blank=True, null=True)),
                ('id_region', models.UUIDField(blank=True, null=True)),
                ('id_city', models.UUIDField(blank=True, null=True)),
                ('id_agency', models.UUIDField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
