# Generated by Django 4.1.5 on 2023-11-08 11:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
