# Generated by Django 4.1.5 on 2023-10-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muser',
            old_name='description',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='muser',
            old_name='code',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='category_year',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='id_agency',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='index',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='invalid',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='ipassword',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='order',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='subcode',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='version',
        ),
    ]
