# Generated by Django 5.0.1 on 2024-04-24 06:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mSchool',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('institution_type', models.IntegerField(choices=[(0, 'NA'), (1, 'ElementarySchool'), (2, 'MiddleSchool'), (3, 'HighSchool'), (4, 'Extra')], default=0)),
                ('img_logo', models.TextField(blank=True, null=True)),
                ('img_banner', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mSchoolCourse',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_section', models.UUIDField(blank=True, null=True)),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('course_title', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mSchoolSection',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_school', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('img_background', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
