# Generated by Django 5.0.1 on 2024-04-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0002_msection_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msection_course',
            name='id_school',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
