# Generated by Django 5.0.1 on 2024-04-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0010_coursedetail_deliver'),
        ('_school', '0004_remove_mschoolcourse_id_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mschoolcourse',
            name='id_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_cm.coursedetail'),
        ),
    ]
