# Generated by Django 5.0.1 on 2024-04-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0005_alter_mschoolcourse_id_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mschoolcourse',
            old_name='id_course',
            new_name='course',
        ),
    ]
