# Generated by Django 5.0.1 on 2024-04-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0007_delete_msection_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mschoolsection',
            name='id_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='_school.mschool'),
        ),
    ]
