# Generated by Django 5.0.1 on 2024-04-26 07:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0009_remove_mschoolcourse_course_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mSchoolNotice',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('date', models.CharField(blank=True, max_length=64)),
                ('id_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_school.mschool')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
