# Generated by Django 5.0.1 on 2024-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0010_mschoolnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mschoolnotice',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
