# Generated by Django 5.0.1 on 2024-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0013_alter_mschoolnotice_id_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mschoolcourse',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='mschoolcourse',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
