# Generated by Django 5.0.1 on 2024-06-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0015_mschoolcourse_modified_course_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('img_icon', models.FileField(blank=True, null=True, upload_to='icon/')),
            ],
        ),
        migrations.RemoveField(
            model_name='mschoolsection',
            name='img_background',
        ),
        migrations.AddField(
            model_name='mschoolsection',
            name='img_icon',
            field=models.FileField(blank=True, null=True, upload_to='icon/'),
        ),
        migrations.AddField(
            model_name='mschoolsection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_school.sectioncategory'),
        ),
    ]
