# Generated by Django 5.0.1 on 2024-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0016_sectioncategory_remove_mschoolsection_img_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mschoolsection',
            name='img_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='img_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
