# Generated by Django 4.1.5 on 2023-11-08 07:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_st', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mDemoStudyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('subtype', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('properties', models.TextField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('id_student', models.UUIDField(blank=True, null=True)),
                ('id_class', models.UUIDField(blank=True, null=True)),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('id_content', models.UUIDField(blank=True, null=True)),
                ('id_base_course', models.UUIDField(blank=True, null=True)),
                ('id_ref_course', models.UUIDField(blank=True, null=True)),
                ('id_clinic_course', models.UUIDField(blank=True, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='mStudyResultN',
            new_name='mStudyResult',
        ),
        migrations.DeleteModel(
            name='mDemoStudyResultN',
        ),
        migrations.AlterModelTable(
            name='mstudyresult',
            table=None,
        ),
    ]
