# Generated by Django 4.1.5 on 2024-04-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_st', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstudyresult',
            name='id_class',
        ),
    ]
