# Generated by Django 4.1.5 on 2023-11-09 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_st', '0002_mdemostudyresult_rename_mstudyresultn_mstudyresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mUserCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('course_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('course_title', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
