# Generated by Django 4.1.5 on 2023-11-08 04:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_cp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('sub_type', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.IntegerField(default=0)),
                ('free', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('subject', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('sub_category', models.IntegerField(default=0)),
                ('language', models.IntegerField(default=0)),
                ('country', models.IntegerField(default=0)),
                ('publisher', models.IntegerField(default=0)),
                ('author', models.IntegerField(default=0)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('id_subject', models.UUIDField(blank=True, null=True)),
                ('id_grade', models.UUIDField(blank=True, null=True)),
                ('id_catergoy', models.UUIDField(blank=True, null=True)),
                ('id_sub_category', models.UUIDField(blank=True, null=True)),
                ('id_language', models.UUIDField(blank=True, null=True)),
                ('id_country', models.UUIDField(blank=True, null=True)),
                ('id_publisher', models.UUIDField(blank=True, null=True)),
                ('id_author', models.UUIDField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
