# Generated by Django 4.1.5 on 2023-10-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_cp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mCourseN',
            new_name='mCourse',
        ),
        migrations.RenameModel(
            old_name='mElementN',
            new_name='mElement',
        ),
    ]
