# Generated by Django 4.1.5 on 2023-11-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_cp', '0002_mcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='melement',
            old_name='content',
            new_name='json_data',
        ),
    ]
