# Generated by Django 4.1.5 on 2023-11-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cp', '0003_rename_content_melement_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcoursebookbranch',
            name='is_demo_available',
            field=models.BooleanField(default=False),
        ),
    ]
