# Generated by Django 4.1.5 on 2024-02-29 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mClass',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_owner', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=64)),
                ('institution_type', models.IntegerField(choices=[(0, 'NA'), (1, 'ElementarySchool'), (2, 'MiddleSchool'), (3, 'HighSchool'), (4, 'Extra')], default=0)),
                ('active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mClassContentAssign',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('id_class', models.UUIDField(blank=True, null=True)),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('id_teacher', models.UUIDField(blank=True, null=True)),
                ('id_student', models.UUIDField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True)),
                ('show_off', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mClassCourse',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_class', models.UUIDField(unique=True)),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mClassInvitation',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_class', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mClassMember',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_user', models.UUIDField(blank=True, null=True)),
                ('id_class', models.UUIDField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Annonymous'), (1, 'Admin'), (2, 'Operator'), (4, 'Producer'), (8, 'Teacher'), (16, 'Student'), (32, 'Parent'), (64, 'User'), (128, 'Manager')], default=0)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mClassPost',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_author', models.UUIDField(blank=True, null=True)),
                ('id_class', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=124)),
                ('content', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'General'), (2, 'Notice')], default=1)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mComment',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_commenter', models.UUIDField(blank=True, null=True)),
                ('id_content', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=124)),
                ('comment', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mReaction',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_user', models.UUIDField(blank=True, null=True)),
                ('id_content', models.UUIDField(blank=True, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='mSingleCourseClass',
            fields=[
                ('mclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_class.mclass')),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('max_member', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('_class.mclass',),
        ),
    ]
