# Generated by Django 4.1.5 on 2024-02-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mclasscourse',
            name='id_class',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='mSingleCourseClass',
        ),
    ]
