# Generated by Django 4.1.5 on 2024-02-29 09:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_class', '0002_alter_mclasscourse_id_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mSingleCourseClass',
            fields=[
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_owner', models.UUIDField(blank=True, null=True)),
                ('id_course', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=64)),
                ('institution_type', models.IntegerField(choices=[(0, 'NA'), (1, 'ElementarySchool'), (2, 'MiddleSchool'), (3, 'HighSchool'), (4, 'Extra')], default=0)),
                ('active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('max_member', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
