# Generated by Django 4.1.5 on 2024-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_class', '0003_msinglecourseclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='msinglecourseclass',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msinglecourseclass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
