# Generated by Django 4.1.5 on 2023-11-29 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(editable=False)),
                ('course', models.TextField(editable=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
