# Generated by Django 4.1.5 on 2023-11-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0006_rename_prince_coursedetail_price'),
        ('_main', '0002_cartcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcourse',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='_cm.coursedetail'),
        ),
        migrations.AlterField(
            model_name='cartcourse',
            name='user',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
