# Generated by Django 4.1.5 on 2023-12-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_user', '0001_initial'),
        ('_main', '0005_orderpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='cartcourse',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='_user.muser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', '주문요청'), ('failed_payment', '결제실패'), ('paid', '결제완료'), ('cancelled', '주문취소')], db_index=True, default='requested', max_length=20, verbose_name='진행상태'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='pay_status',
            field=models.CharField(choices=[('ready', '결제 준비'), ('paid', '결제 완료'), ('cancelled', '결제 취소'), ('failed', '결제 실패')], default='ready', max_length=20, verbose_name='결제상태'),
        ),
    ]
