# Generated by Django 4.1.5 on 2023-12-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_main', '0006_alter_order_options_alter_cartcourse_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(verbose_name='코스 총 금액')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='포인트')),
            ],
        ),
    ]
