# Generated by Django 4.1.5 on 2023-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_main', '0008_pointcharge_delete_cartbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(editable=False)),
                ('points', models.PositiveIntegerField(default=0, verbose_name='보유포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
