# Generated by Django 5.0.1 on 2024-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='courseId',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
