# Generated by Django 4.1.5 on 2023-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='title',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='courseId',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='courseSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='courseTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
