# Generated by Django 4.1.5 on 2023-11-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0002_remove_coursedetail_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='producer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='thumnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
