# Generated by Django 4.1.5 on 2023-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0003_coursedetail_producer_coursedetail_thumnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='isTest',
            field=models.BooleanField(default=False),
        ),
    ]
