# Generated by Django 5.0.1 on 2024-03-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0003_coursereset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='courseSummary',
            new_name='course_summary',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='courseTitle',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='desc',
            new_name='descript',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='isTest',
            new_name='is_test',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='courseId',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='id_course',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
