# Generated by Django 4.1.5 on 2023-11-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0004_coursedetail_istest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='cost',
            new_name='prince',
        ),
    ]
