# Generated by Django 5.0.1 on 2024-03-22 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0004_rename_coursesummary_coursedetail_course_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselanding',
            old_name='courseId',
            new_name='id_course',
        ),
        migrations.AlterField(
            model_name='courselanding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
