# Generated by Django 5.0.1 on 2024-03-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0005_rename_courseid_courselanding_id_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselanding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
