# Generated by Django 4.1.5 on 2023-11-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0005_rename_cost_coursedetail_prince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='prince',
            new_name='price',
        ),
    ]
