# Generated by Django 4.1.5 on 2023-12-29 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0006_rename_prince_coursedetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
