# Generated by Django 5.0.1 on 2024-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0007_rename_id_course_coursedetail_courseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselanding',
            name='id_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
