# Generated by Django 4.1.5 on 2023-12-29 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0007_courselanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselanding',
            name='courseId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
