# Generated by Django 5.0.1 on 2024-04-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0008_courselanding_id_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereset',
            name='deliver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
