# Generated by Django 5.0.1 on 2024-04-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0009_coursereset_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='deliver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
