# Generated by Django 4.1.5 on 2023-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0009_alter_courselanding_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselanding',
            name='courseId',
            field=models.UUIDField(),
        ),
    ]
