# Generated by Django 5.0.1 on 2024-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0010_coursedetail_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='courseId',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
