# Generated by Django 5.0.1 on 2024-05-29 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0011_alter_coursedetail_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
