# Generated by Django 5.0.1 on 2024-08-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_cm', '0015_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
